version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3007:3000'
      - '5557:5555'
    volumes:
      - ./realDB:/app/realDB
      - ./public:/app/public
    command: "npm run start"
    restart: always
